# Generated by Django 4.1.13 on 2023-12-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0005_alter_product_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orderstats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product_cart',
            name='orderstats',
            field=models.BooleanField(default=False),
        ),
    ]
