# Generated by Django 4.1.13 on 2023-12-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipping', 'Shipping')], default='Pending', max_length=50),
        ),
    ]
